#Customer port
server:
  port: 8081

#Customer logging app
logging:
  level:
    com.compony.springexample: debug

#Connecting and configuring the database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

